"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var STATUSCODE_ENUM;
(function (STATUSCODE_ENUM) {
    STATUSCODE_ENUM[STATUSCODE_ENUM["UNKNOWN_ERROR"] = 0] = "UNKNOWN_ERROR";
    STATUSCODE_ENUM[STATUSCODE_ENUM["FORM_REQUIREMENT_ERROR"] = 1] = "FORM_REQUIREMENT_ERROR";
    STATUSCODE_ENUM[STATUSCODE_ENUM["PAGE_NOT_FOUND"] = 2] = "PAGE_NOT_FOUND";
    STATUSCODE_ENUM[STATUSCODE_ENUM["RESOURCE_NOT_FOUND"] = 3] = "RESOURCE_NOT_FOUND";
    STATUSCODE_ENUM[STATUSCODE_ENUM["RESOURCE_ALREADY_EXIST"] = 4] = "RESOURCE_ALREADY_EXIST";
    STATUSCODE_ENUM[STATUSCODE_ENUM["SUCCESS"] = 5] = "SUCCESS";
    STATUSCODE_ENUM[STATUSCODE_ENUM["LOAN_PAID"] = 6] = "LOAN_PAID";
    STATUSCODE_ENUM[STATUSCODE_ENUM["LOAN_NOT_PAID"] = 7] = "LOAN_NOT_PAID";
    STATUSCODE_ENUM[STATUSCODE_ENUM["NO_LOAN_OWED"] = 8] = "NO_LOAN_OWED";
    STATUSCODE_ENUM[STATUSCODE_ENUM["NO_BANK_ACCOUNT"] = 9] = "NO_BANK_ACCOUNT";
    STATUSCODE_ENUM[STATUSCODE_ENUM["LOW_CREDIT_SCORE"] = 10] = "LOW_CREDIT_SCORE";
})(STATUSCODE_ENUM || (STATUSCODE_ENUM = {}));
